# Generated by Django 3.1.7 on 2021-03-13 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('access_key', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tempEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.IntegerField()),
                ('time', models.IntegerField()),
                ('place', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='temperature.location')),
            ],
        ),
    ]
